import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { CapabilityCodec } from '../../packages/capability-core/src/index.js';
import { Store } from '../../packages/evidence-core/src/index.js';
import { ExecutionBroker, BrokerError, ToolRegistry, createDemoRegistry, type ToolDefinition } from '../../packages/execution-broker/src/index.js';
import type { Decision } from '../../packages/shared-schema/src/index.js';

const agent = { kind: 'agent', agentId: 'agent-1' } as const;
const request = { agentId: 'agent-1', action: 'production.deploy', tool: 'demo.deploy.execute', resource: 'release-1', estimatedCostUsd: 0 };
function setup(tool: ToolDefinition | ToolRegistry | null = null, options: ConstructorParameters<typeof ExecutionBroker>[3] = {}) {
  const store = new Store(':memory:');
  const codec = new CapabilityCodec(randomBytes(32), { clock: () => Date.parse('2026-09-09T12:00:00.000Z') });
  const registry = tool instanceof ToolRegistry ? tool : new ToolRegistry(); if (tool && !(tool instanceof ToolRegistry)) registry.register(tool);
  const decision: Decision = { decisionId: 'decision-1', agentId: 'agent-1', decision: 'ALLOW', reason: 'approved', severity: 'info', policyVersion: '1', policyHash: 'policy-1', requiresEvidence: true, timestamp: '2026-09-09T11:59:00.000Z', request, approvalReference: null };
  store.put('decision', decision.decisionId, decision);
  return { store, broker: new ExecutionBroker(store, codec, registry, options), decision };
}
const demo = (dir: string): ToolRegistry => createDemoRegistry(dir);

test('rejects unknown tool and does not invoke an unregistered handler', () => { const { broker, store } = setup(); assert.throws(() => broker.issue(agent, 'decision-1'), (e: unknown) => e instanceof BrokerError && e.status === 403); assert.equal(store.events().filter(e => (e as { state?: string }).state === 'STARTED').length, 0); store.close(); });
test('registry metadata does not expose handlers', async () => { const registry = new ToolRegistry(); let calls = 0; registry.register({ name: 'x', action: 'a', resourceType: 'infrastructure', allowedOperations: ['write'], networkRequired: false, credentialsRequired: [], handler: () => { calls++; } }); const metadata = registry.get('x'); assert.ok(metadata); assert.equal('handler' in metadata, false); assert.equal('handler' in registry.list()[0]!, false); await assert.rejects(() => registry.invoke('x', {} as never), /broker-only/); assert.equal(calls, 0); });
test('concurrent issuance creates one capability and one issued path', async () => { const { broker, store } = setup(demo(resolve('data', 'test-artifacts'))); const results = await Promise.allSettled(Array.from({ length: 10 }, () => Promise.resolve().then(() => broker.issue(agent, 'decision-1')))); assert.equal(results.filter(result => result.status === 'fulfilled').length, 1); assert.equal(results.filter(result => result.status === 'rejected' && result.reason instanceof BrokerError && result.reason.status === 409).length, 9); assert.equal(store.list('execution.capability').length, 1); assert.equal(store.events().filter(event => (event as { state?: string }).state === 'CAPABILITY_ISSUED').length, 1); store.close(); });
for (const state of ['BLOCK', 'HOLD'] as const) test(`refuses ${state} issuance`, () => { const { broker, store, decision } = setup(demo(resolve('data', 'test-artifacts'))); decision.decision = state; store.put('decision', decision.decisionId, decision); assert.throws(() => broker.issue(agent, decision.decisionId), (e: unknown) => e instanceof BrokerError && e.status === 403); store.close(); });
test('enforces binding, revocation, stale policy, and replay checks', async () => { const { broker, store } = setup(demo(resolve('data', 'test-artifacts'))); const issued = broker.issue(agent, 'decision-1'); await assert.rejects(() => broker.redeem(agent, { token: issued.token, tool: 'wrong', resource: 'release-1', operation: 'write' }), /binding/); let revokedState = false; const revoked = setup(demo(resolve('data', 'test-artifacts')), { isAgentRevoked: () => revokedState }); const revokedIssued = revoked.broker.issue(agent, 'decision-1'); revokedState = true; await assert.rejects(() => revoked.broker.redeem(agent, { token: revokedIssued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }), /revoked/); let staleState = true; const stale = setup(demo(resolve('data', 'test-artifacts')), { isPolicyCurrent: () => staleState }); const staleIssued = stale.broker.issue(agent, 'decision-1'); staleState = false; await assert.rejects(() => stale.broker.redeem(agent, { token: staleIssued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }), /stale/); await broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }); await assert.rejects(() => broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }), /consumed/); store.close(); revoked.store.close(); stale.store.close(); });
test('demo writes a deterministic sandbox artifact without secrets', async () => { const dir = mkdtempSync(resolve('data', 'test')); const { broker, store } = setup(demo(dir)); const issued = broker.issue(agent, 'decision-1'); const result = await broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }); assert.equal(result.state, 'SUCCEEDED'); const contents = readFileSync(resolve(dir, `${issued.payload.execution_id}.json`), 'utf8'); assert.match(contents, /production.deploy/); assert.equal(contents.includes('secret'), false); assert.equal(JSON.stringify(result).includes('secret'), false); rmSync(dir, { recursive: true, force: true }); store.close(); });
test('handler failure does not persist sensitive error details', async () => { const secret = 'handler-secret-value'; const resultHash = 'a'.repeat(64); const tool: ToolDefinition = { name: 'demo.deploy.execute', action: 'production.deploy', resourceType: 'infrastructure', allowedOperations: ['write'], networkRequired: false, credentialsRequired: [], handler: async () => { throw Object.assign(new Error(`handler failed: ${secret}`), { resultHash }); } }; const { broker, store } = setup(tool); const issued = broker.issue(agent, 'decision-1'); await assert.rejects(() => broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }), (error: unknown) => error instanceof BrokerError && error.status === 500 && error.message === 'Handler failed' && !error.message.includes(secret)); const events = store.events(); assert.equal(JSON.stringify(events).includes(secret), false); const execution = broker.execution(agent, issued.payload.execution_id); assert.equal(execution.reason, 'Protected handler failed'); assert.equal(execution.result_hash, resultHash); assert.equal(JSON.stringify(execution).includes(secret), false); assert.equal(JSON.stringify(broker.executions(agent, 'agent-1')).includes(secret), false); store.close(); });
test('handler failure records FAILED and ten concurrent redemptions invoke once', async () => { let calls = 0; const tool: ToolDefinition = { name: 'demo.deploy.execute', action: 'production.deploy', resourceType: 'infrastructure', allowedOperations: ['write'], networkRequired: false, credentialsRequired: [], handler: async () => { calls++; throw new Error('boom'); } }; const { broker, store } = setup(tool); const issued = broker.issue(agent, 'decision-1'); await assert.rejects(() => broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }), /Handler failed/); assert.equal(calls, 1); assert.equal(store.events().filter(e => (e as { state?: string }).state === 'FAILED').length, 1); store.close(); const concurrent = setup({ ...tool, handler: async () => { calls++; return { ok: true }; } }); const issued2 = concurrent.broker.issue(agent, 'decision-1'); const results = await Promise.allSettled(Array.from({ length: 10 }, () => concurrent.broker.redeem(agent, { token: issued2.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }))); assert.equal(results.filter(result => result.status === 'fulfilled').length, 1); assert.equal(calls, 2); concurrent.store.close(); });
test('missing evidence path prevents invocation', async () => { let calls = 0; const { broker, store } = setup({ name: 'demo.deploy.execute', action: 'production.deploy', resourceType: 'infrastructure', allowedOperations: ['write'], networkRequired: false, credentialsRequired: [], handler: () => { calls++; } }); const issued = broker.issue(agent, 'decision-1'); store.append = () => { throw new Error('unavailable'); }; await assert.rejects(() => broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' })); assert.equal(calls, 0); store.close(); });
test('execution reads are isolated and transitions are append-only', async () => { const { broker, store } = setup(demo(resolve('data', 'test-artifacts'))); const issued = broker.issue(agent, 'decision-1'); await broker.redeem(agent, { token: issued.token, tool: 'demo.deploy.execute', resource: 'release-1', operation: 'write' }); assert.equal(broker.executions(agent, 'agent-1').length, 1); assert.throws(() => broker.execution({ kind: 'agent', agentId: 'other' }, issued.payload.execution_id), /Access denied/); assert.equal(store.events().filter(e => (e as { type?: string }).type === 'execution.transition').length >= 5, true); store.close(); });