import assert from 'node:assert/strict';
import { execPath } from 'node:process';
import { mkdtemp, readFile, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { ChildProcessIsolationRunner, IsolationError, type IsolatedExecutionRequest } from '../../packages/isolation-runner/src/index.js';

async function workspace(): Promise<string> { return mkdtemp(join(tmpdir(), 'tna-isolation-')); }
function request(root: string, overrides: Partial<IsolatedExecutionRequest> = {}): IsolatedExecutionRequest { return { execution_id: 'execution-test', agent_id: 'agent-test', tool: 'tool.test', operation: 'run', command: execPath, args: ['-e', 'process.stdout.write("ok")'], workspace: root, cwd: '.', env: {}, runtime_limit_ms: 1000, stdout_limit_bytes: 4096, stderr_limit_bytes: 4096, output_limit_bytes: 8192, no_network: { requested: true, mode: 'preflight-only' }, ...overrides }; }
async function close(root: string): Promise<void> { await rm(root, { recursive: true, force: true }); }

test('passes only the explicit environment allowlist and safe fixed values', async () => {
  const root = await workspace();
  try {
    await assert.rejects(() => new ChildProcessIsolationRunner().run(request(root, { env: { CAPABILITY_SHOULD_NOT_PASS: 'no' } as never })), (error: unknown) => error instanceof IsolationError && error.code === 'INVALID_ENVIRONMENT');
    const result = await new ChildProcessIsolationRunner().run(request(root, { env: { ALLOWED_VALUE: 'yes' }, args: ['-e', 'process.stdout.write(JSON.stringify({ allowed: process.env.ALLOWED_VALUE, capability: process.env.CAPABILITY_SHOULD_NOT_PASS, execution: process.env.TNA_EXECUTION_ID, tmp: process.env.TMP }))'] }));
    assert.equal(result.state, 'SUCCEEDED'); const output = JSON.parse(result.stdout.preview) as Record<string, string | undefined>;
    assert.equal(output.allowed, 'yes'); assert.equal(output.capability, undefined); assert.equal(output.execution, 'execution-test'); assert.equal(output.tmp, root);
  } finally { await close(root); }
});
test('rejects unsafe cwd forms before spawn', async () => { const root = await workspace(); try { await assert.rejects(() => new ChildProcessIsolationRunner().run(request(root, { cwd: 'bad\u0000path' })), (error: unknown) => error instanceof IsolationError && error.code === 'INVALID_REQUEST'); for (const cwd of ['../nested', 'safe/../escape', 'C:/absolute', '\\\\server\\share', 'nested//path', 'nested\\\\path', root]) await assert.rejects(() => new ChildProcessIsolationRunner().run(request(root, { cwd })), (error: unknown) => error instanceof IsolationError && error.code === 'INVALID_CWD'); } finally { await close(root); } });
test('rejects a symlink escape when the platform permits symlink creation', async t => { const root = await workspace(); const outside = await workspace(); const link = join(root, 'escape'); try { try { await symlink(outside, link, 'junction'); } catch (error) { t.skip(`symlink/junction unavailable: ${error instanceof Error ? error.message : String(error)}`); return; } await assert.rejects(() => new ChildProcessIsolationRunner().run(request(root, { cwd: 'escape' })), (error: unknown) => error instanceof IsolationError && error.code === 'WORKSPACE_ESCAPE'); } finally { await close(root); await close(outside); } });
test('treats shell metacharacters as an argument, never as shell syntax', async () => { const root = await workspace(); try { const argument = '$(echo injected); & not-a-command'; const result = await new ChildProcessIsolationRunner().run(request(root, { args: ['-e', 'process.stdout.write(process.argv[1] ?? "")', argument] })); assert.equal(result.stdout.preview, argument); assert.equal(result.state, 'SUCCEEDED'); } finally { await close(root); } });
test('returns FAILED for non-zero exit and child errors', async () => { const root = await workspace(); try { const failed = await new ChildProcessIsolationRunner().run(request(root, { args: ['-e', 'process.exit(7)'] })); assert.equal(failed.state, 'FAILED'); assert.equal(failed.reason, 'non_zero_exit'); assert.equal(failed.exit_code, 7); const missing = await new ChildProcessIsolationRunner().run(request(root, { command: join(root, 'missing-command') })); assert.equal(missing.state, 'FAILED'); assert.equal(missing.reason, 'child_error'); } finally { await close(root); } });
test('terminates on runtime and output limits, with bounded previews', async () => { const root = await workspace(); try { const timeout = await new ChildProcessIsolationRunner().run(request(root, { runtime_limit_ms: 50, args: ['-e', 'setInterval(() => {}, 1000)'] })); assert.equal(timeout.state, 'TERMINATED'); assert.equal(timeout.reason, 'runtime_limit'); const output = await new ChildProcessIsolationRunner().run(request(root, { stdout_limit_bytes: 32, output_limit_bytes: 32, args: ['-e', 'process.stdout.write("x".repeat(1000000))'] })); assert.equal(output.state, 'TERMINATED'); assert.equal(output.reason, 'output_limit'); assert.ok(output.stdout.preview.length <= 32); assert.ok(output.stdout.bytes >= 32); const error = await new ChildProcessIsolationRunner().run(request(root, { stderr_limit_bytes: 32, output_limit_bytes: 32, args: ['-e', 'process.stderr.write("e".repeat(1000000))'] })); assert.equal(error.state, 'TERMINATED'); assert.equal(error.reason, 'output_limit'); assert.ok(error.stderr.preview.length <= 32); } finally { await close(root); } });
test('reports network as unenforced and rejects strict network mode', async () => { const root = await workspace(); try { const result = await new ChildProcessIsolationRunner().run(request(root)); assert.equal(result.network.enforcement, 'not-enforced'); assert.equal(result.network.mode, 'preflight-only'); await assert.rejects(() => new ChildProcessIsolationRunner({ strictNetwork: true }).run(request(root)), (error: unknown) => error instanceof IsolationError && error.code === 'NETWORK_ENFORCEMENT_UNAVAILABLE'); } finally { await close(root); } });
test('does not leave the timed-out child alive', async () => { const root = await workspace(); const marker = join(root, 'alive'); try { const result = await new ChildProcessIsolationRunner().run(request(root, { runtime_limit_ms: 50, args: ['-e', `setInterval(() => require('node:fs').writeFileSync(${JSON.stringify(marker)}, 'alive'), 10)`] })); assert.equal(result.reason, 'runtime_limit'); await new Promise(resolve => setTimeout(resolve, 150)); const first = await readFile(marker, 'utf8').catch(() => ''); await new Promise(resolve => setTimeout(resolve, 150)); const second = await readFile(marker, 'utf8').catch(() => ''); assert.equal(second, first); } finally { await close(root); } });
test('does not leave a descendant alive after timeout or output termination', async () => { const root = await workspace(); const marker = join(root, 'descendant-alive'); const descendant = `const fs=require('node:fs');let n=0;setInterval(()=>fs.writeFileSync(${JSON.stringify(marker)},String(++n)),10);`; const parent = `require('node:child_process').spawn(process.execPath,['-e',${JSON.stringify(descendant)}],{stdio:'ignore'});setTimeout(()=>{},1000);`; try { for (const overrides of [{ runtime_limit_ms: 50 }, { stdout_limit_bytes: 32, output_limit_bytes: 32, args: ['-e', `${parent};process.stdout.write('x'.repeat(1000000))`] }]) { await rm(marker, { force: true }); const result = await new ChildProcessIsolationRunner().run(request(root, { ...overrides, args: overrides.args ?? ['-e', parent] })); assert.equal(result.state, 'TERMINATED'); const first = await readFile(marker, 'utf8').catch(() => ''); await new Promise(resolve => setTimeout(resolve, 150)); const second = await readFile(marker, 'utf8').catch(() => ''); assert.equal(second, first); } } finally { await close(root); } });